env:
# ENCRYPTED
  RCLONECONFIG_DRIVE: "ENCRYPTED[!364a5e503b6414e4ac72b4ffe170fa024050c195503bef187c65d2f528407e3003ef7332449ce8ea809f1cc5456bb44f!]"
  TG_TOKEN: "ENCRYPTED[!85a8b0e0604e1e0d4f8898e7b7ec5547c1e4916a1f160b529f71a1a57b382e075a20c9fabcf2382cd6f5aff783efd7ca!]"
  TG_CHAT_ID: "ENCRYPTED[!d135f1c4785dded7963d9c0de8c666f14ce3d1915c94b32c606998eda214681ee357f020f1c79e636532c345919ef370!]"
  EMAIL: "ENCRYPTED[!db3056209b367678c4422cd0528086498eec398c2781092b675d6da5d497bf8b84d26deec2fe77805767a427de115e1b!]"
  UNAME: "ENCRYPTED[!c7b6b22b94dcd039fe0df486435ca2c27c96caf5942c19c0aafe9c14cf7dac10b625ede3dde05d33cf1edfcce89db7e8!]"

# FLAG
  WORKDIR: "/tmp"
  CIRRUS_CLONE_DEPTH: "1"

task:
  name: "LineageOS Build"
  stateful: true
  timeout_in: 120m
  container:
    image: anggit86/ubuntu:22.04
    cpu: 8
    memory: 32G

  Memuat-ccache_background_script:
     - ./script/load_ccache.sh

  Repo-pribadi_script:
     - git config --global user.name "$UNAME"
     - git config --global user.email "$EMAIL"

  Sinkronasi-rom_script:
     - curl -s https://api.telegram.org/bot$TG_TOKEN/sendMessage -d chat_id=$TG_CHAT_ID -d text="Start sync Source"
     - ./script/sync.sh
     - curl -s https://api.telegram.org/bot$TG_TOKEN/sendMessage -d chat_id=$TG_CHAT_ID -d text="Sync Completed!"
     
  Membangun-rom_script:
     - ./script/building.sh
     
  Ccache-informasi_background_script:
     - set -e
     - export CCACHE_DIR=$WORKDIR/ccache
     - ccache -s

  Mengunggah-build_script:
     - ./script/ziping.sh
